from smoketest.mylib.utils import Utils
import sys, os, time

__author__ = 'rnaude'


def main():
    printTree = PrintTree
    printTree.print_tree(Utils.log_dir() + '\\logs\\')

class PrintTree():
    def __init__(self):
        pass

    @classmethod
    def print_tree(cls, results_dir):
        import xml.etree.ElementTree as ET
        from xml.etree.ElementTree import Comment

        root = ET.Element("resultsFiles")
        # doc = ET.SubElement(root, 'logs')
        root.append(Comment('Do Not Change. Auto Generated by print_tree() in utils.py'))

        dir_contents = os.walk(results_dir).next()
        for date_dir in dir_contents[1]:
            dir_next = os.walk(results_dir + '\\' + date_dir).next()
            field1 = ET.SubElement(root, "testDate")
            field1.set("date", date_dir.replace('_', ' '))
            for date_file in dir_next[2]:
                field2 = ET.SubElement(field1, "fileName")
                field2.set("file", date_file.replace('_', ' '))
                # field2.set('url', dir_next[0] + '\\' + date_file)
                field2.set('url', os.path.join(os.path.relpath(dir_next[0], date_file)))
            screenshots = os.walk(results_dir + '\\' + date_dir + '\\screenshots').next()
            el = ET.SubElement(field1, 'screenshots')
            for screenshot in screenshots[2]:
                print('cwd', os.path.abspath(os.getcwd()))
                field3 = ET.SubElement(el, 'screenshot')
                field3.set('error', screenshot)
                # field3.set('url', screenshots[0] + '\\' + screenshot)
                field3.set('url', os.path.join(os.path.relpath(screenshots[0]), screenshot))

        tree = ET.ElementTree(root)
        tree.write(os.path.join(os.path.relpath(Utils.log_dir()), 'logs\\testDates.xml'))

        dir_contents = os.walk(results_dir).next()
        for cont in dir_contents[1]:
            print cont

if __name__ == '__main__':
    main()

